// This is a template for creating maps for MARS. Use 'map' to create key-value pairs
// between SESAR's field names and your organization's field names. Be sure to delete
// the entries that do not map to your organization's data. Some of SESAR's fields
// are automatically generated by MARS. These fields, denoted with 'AUTOMATIC' in the
// comments, can be overritten if need be.

// Usually, the relationship between a SESAR field and an organization's field will
// be one-to-one. However, MARS supports a one-to-many mapping for some of SESAR's
// fields. This is denoted in the 'map' by including an array of field names rather
// than just a string.

let map = {
  user_code: ,                // (ATOMATIC) SESAR user code, five digits e.g. IESES.
  sample_type: ,              // The type of sample which comes from a SESAR controlled list
  name: ,                     // The Name of the sample.
  material: ,                 // The material of the sample which comes from a SESAR controlled list
  igsn: ,                     // (AUTOMATIC) The 9-digit IGSN of the sample
  parent_igsn: ,              // The IGSN of the parent of the current sample
  is_private: ,               // Value should be 1 for private and 0 or null for public
  publish_date: ,             // Date on which sample set to public is available for global search and display YYYY-MM-DD
  classification: ,           // Classification, controlled list, classification specific to material
  classification_comment: ,   // Comment about classification
  field_name: ,               // Taxonomy, informal classification of sample
  description: ,              // Free text to describe features of a sample such as its components
  age_min: ,                  // Numerical value for the minimum age of a sample
  age_max: ,                  // Numerical value for the maximum age of a sample
  age_unit: ,                 // Unit for the age provided
  geological_age: ,           // Age of a sample as described by the stratigraphic era, period, state, etc., e.g. Cretaceous
  geological_unit: ,          // A body of rock established as a distinct entity in the classification of Earth's rocks, e.g. Coconio Sandstone
  collection_method: ,        // Method by which the sample was collected, e.g. Dredging, Manual
  collection_method_descr: ,  // Additional information about the collection Method
  size: ,                     // Size of the registered object, such as the dimension of a specimen, the length of a core, or the weight of a dredge
  size_unit: ,                // Unit for the numerical value provided for 'size'
  sample_comment: ,           // Any free text comment about the sample
  purpose: ,                  // The purpose for collecting the sample. e.g. paleomagnetism
  latitude: ,                 // Latitude of the location where the sample was collected. (Start latitude for linear sampling features)
  longitude: ,                // Longitude of the location where the sample was collected. (Start longitude for linear sampling features)
  latitude_end: ,             // End latitude of the location where the sample was collected (WGS84)
  longitude_end: ,            // End longitude of the location where the sample was collected (WGS84)
  elevation: ,                // Elevation at which a sample was collected (in meters). Use negative values for depth below sea level
  elevation_end: ,            // End elevation at which a sample was collected
  elevation_unit: ,           // Unit for the elevation provided. e.g. Meters, Feet.
  vertical_datum: ,           // Surface of zero elevation to which heights of various points are referred e.g. NAVD88, MSL
  northing: ,                 // UTM northing (m): a number between 0 and 10,000,000 (Coordinate system: UTM NAD83)
  easting: ,                  // UTM easting (m): a number between 0 and 834,000 (Coordinate system: UTM NAD83)
  zone: ,                     // UTM zone, use A to Z to specify hemisphere zone. e.g., 11N
  navigation_type: ,          // Navigation type, controlled list
  primary_location_type: ,    // Physiographic feature or type of feture that your sample was collected from
  primary_location_name: ,    // Name of physiographic feature or the name of the primary_location_type
  location_description: ,     // Free text description of the location_description
  locality: ,                 // Name of the specific place where your sample was collected. This could be the name of a mine, a volcanic field,
  locality_description: ,     // Additional information about the specific place where your sample was collected
  country: ,                  // Country where the sample was collected, controlled list
  privince: ,                 // State or Province where the sample was collected
  county: ,                   // County where the sample was collected.
  city: ,                     // City or Township where the sample was collected
  cruise_field_prgrm: ,       // Name or identifier of the field program during which the sample was collected.
  platform_type: ,            // Type of platform for the cruise. Suggested list.
  platform_name: ,            // Name of platform for cruise
  platform_descr: ,           // Description of the platform for the cruise
  launch_platform_name: ,     // Name of the launch platform that collected the sample
  launch_id: ,                // Further identifying information about the launch.
  launch_type_name: ,         // The type of launch used to collect the sample e.g. 'HOV'
  collector: ,                // Name of the person who collected the sample or name of chief scientist for larger field programs
  collector_detail: ,         // Institution, address, & email of the collector or chief scientist
  collection_start_date: ,    // Date when the sample was collected. The format is YYYY-MM-DDTHH:MM:SSZ
  collection_end_date: ,      // Date when the sample collection was finished
  collection_date_precision: ,// Precision to display the collection date and times
  current_archive: ,          // Name of institution, museum or repository where the sample is currently stored
  current_archive_contact: ,  // Address and/or email of the person who should be contacted for information about the sample
  original_archive: ,         // Name of institution, museum, or repository where the sample was originally stored
  original_archive_contact: , // Address and/or email of the person who should be contacted for information about the sample's original archive
  depth_min: ,                // Minimum depth at which a sample was collected from its parent core
  depth_max: ,                // Maximum depth at which a sample was collected from its parent core
  depth_scale: ,              // Unit in which the depth is provided e.g. MBSF
  sample_other_names: ,       // Other names for the sample. Can be multiple
}

// In the likely even that your data does not perfectly map to the values that SESAR
// accepts, you can place custom functions in the logic object. This allows you
// to govern how your values are altered in order to be placed in SESAR's database.

let logic = {
  // place your logic functions here
}

let combinations = {
  // place your combination functions here (only for fields where multiple fields are mapped)
}

// The return makes your map and logic objects available to MARS
return {map, logic}
